name: emaxapp
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  font_awesome_flutter: ^9.2.0
  http: ^0.13.4
  dio: ^4.0.4
  # path: ^1.8.0
  # sqflite: ^2.0.0+4
  # path_provider: ^2.0.6
  firebase_core: ^1.10.6
  cloud_firestore: ^3.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  


flutter:

  
  uses-material-design: true


  assets:
    - assets/image/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf